spring.application.name=regy-inventory

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/regy_inventory
spring.datasource.username=postgres
spring.datasource.password=A

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret=XZhZ/Sv24qak0kPIzEYRPuGJ/LW/9R6XxTe/MHHw5Hs=
jwt.expiration=86400000